version: "3.9"

services:

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: expensetracker
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/expensetracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    command: ["java","-jar","/app/expensetracker.jar"]

volumes:
  dbdata:
